### ISSUE TITLE
Static Library to Save Compile Time

### ISSUE THREAD

**Issue by dpott197** [strike65/SwiftyStats#1]
Thanks for creating this library. Unfortunately, the build times are a bit long. Could you please create a static library for this?

In the meantime, I'm attempting to use [Cocoapods-Binary](https://github.com/leavez/cocoapods-binary) to prevent recompilation. I'm running into the follow error.

`pod 'SwiftyStats', :binary => true`

[x] error: SWIFT_VERSION '5' is unsupported, supported versions are: 3.0, 4.0, 4.2. (in target 'SwiftyStats')

I followed https://stackoverflow.com/questions/55585062/xcode-keeps-showing-1-swift-version-5-0-is-unsupported-supported-versions-a.

Any help would be appreciated. Thanks, again.

**Comment by dpott197** [comment]
Resolved by using xcode-select to switch from 10.1 to 10.2.1

**Comment by strike65** [comment]
Hi!
Compile times now way faster than before. Thanks for using the library.
