### ISSUE TITLE
SSDeprecated.swift throws no such module exception on Linux

### ISSUE THREAD

**Issue by THaar50** [strike65/SwiftyStats#5]
Deprecation warnings prevent compilation on Linux. I believe the reason is missing support for os.log on Linux.

Error:
SwiftyStats/SwiftyStats/CommonSource/DEPRECATIONS/SSDeprecated.swift:26:8: error: no such module 'os.log'

Solution:
I believe you have to make the import of os.log conditional on the used operating system:
#if os(macOS) || os(iOS)
import os.log
#endif

**Comment by strike65** [comment]
Thanks. I will fix this soon.

**Comment by strike65** [comment]
Should be fixed in 1.1.5.
